all:
  hosts:
    node1:
      ansible_host: 193.61.36.31
      ip: 193.61.36.31
      access_ip: 193.61.36.31
      ansible_user: dorian
    node2:
      ansible_host: 193.61.36.26
      ip: 193.61.36.26
      access_ip: 193.61.36.26
      ansible_user: dorian
    node3:
      ansible_host: 193.61.36.27
      ip: 193.61.36.27
      access_ip: 193.61.36.27
      ansible_user: dorian
    node4:
      ansible_host: 193.61.36.11
      ip: 193.61.36.11
      access_ip: 193.61.36.11
      ansible_user: dorian
    node5:
      ansible_host: 193.61.36.18
      ip: 193.61.36.18
      access_ip: 193.61.36.18
      ansible_user: dorian
#    node6:
#      ansible_host: 193.61.36.56
#      ip: 193.61.36.56
#      access_ip: 193.61.36.56
#      ansible_user: dorian
#    node7:
#      ansible_host: 193.61.36.50
#      ip: 193.61.36.50
#      access_ip: 193.61.36.50
#      ansible_user: dorian
#    node8:
#      ansible_host: 193.61.36.53
#      ip: 193.61.36.53
#      access_ip: 193.61.36.53
#      ansible_user: dorian
#    node9:
#      ansible_host: 193.61.36.38
#      ip: 193.61.36.38
#      access_ip: 193.61.36.38
#      ansible_user: dorian
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
#        node6:
#        node7:
#        node8:
#        node9:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
